precision: 32
max_epochs: 15 #75
num_nodes: 1
gpus: -1
sync_batchnorm: True
default_root_dir: ${exp_dir}
num_sanity_val_steps: 0
limit_val_batches: 1.0
accumulate_grad_batches: 1
gradient_clip_val: 5.0
replace_sampler_ddp: False
resume_from_checkpoint: #/home/nas4/user/yh/ai_hub_korean/outputs/2023-10-16/01-50-46/Tr2DZ/Tr2DZ_zeroshot_small_v2/epoch=18.ckpt